import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, CheckCircle2, Mic, SkipForward } from 'lucide-react';
import { api } from '../services/api';

const defaults = { role: '', type: 'Mixed', difficulty: 'Medium', duration: '20 minutes', company: '', jobDescription: '' };

export default function MockInterview({ dashboard }) {
  const [setup, setSetup] = useState({ ...defaults, role: dashboard.target_role || '' });
  const [questions, setQuestions] = useState([]);
  const [index, setIndex] = useState(0);
  const [answer, setAnswer] = useState('');
  const [reviews, setReviews] = useState([]);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [listening, setListening] = useState(false);
  const recognitionRef = useRef(null);
  const [error, setError] = useState('');
  useEffect(() => { api.interviewHistory().then((result) => setHistory(result.history)).catch(() => {}); }, []);
  const update = (key) => (event) => setSetup((current) => ({ ...current, [key]: event.target.value }));
  const start = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await api.questions(setup.role || dashboard.target_role || 'Target role', dashboard.resume?.sections?.skills || dashboard.profile?.skills || [], setup.jobDescription, setup.type, setup.difficulty); setQuestions(result.questions); setIndex(0); setReviews([]); setAnswer(''); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  const startVoice = () => { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) return setError('Voice input is unavailable in this browser. Use the text answer box instead.'); const recognition = new SpeechRecognition(); recognition.lang = 'en-US'; recognition.interimResults = false; recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onerror = () => { setListening(false); setError('Voice input could not be started. Use the text answer box instead.'); }; recognition.onresult = (event) => setAnswer((current) => `${current} ${event.results[0][0].transcript}`.trim()); recognitionRef.current = recognition; recognition.start(); };
  const submit = async () => { if (!answer.trim()) return setError('Write an answer before continuing.'); setLoading(true); setError(''); try { const review = await api.evaluate(setup.role, questions[index].question, answer, setup.type); const nextReviews = [...reviews, { question: questions[index].question, answer, review }]; setReviews(nextReviews); setAnswer(''); if (review.score < 60 && index + 1 < questions.length) setQuestions((current) => [...current.slice(0, index + 1), { type: 'Follow-up', question: `Can you clarify the result or evidence from your previous answer?` }, ...current.slice(index + 1)]); if (index + 1 < questions.length) setIndex(index + 1); else setIndex(questions.length); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  if (index >= questions.length && reviews.length) return <Report reviews={reviews} history={history} onRestart={() => { setQuestions([]); setReviews([]); setIndex(0); }} />;
  if (!questions.length) return <Setup setup={setup} update={update} start={start} loading={loading} error={error} />;
  const question = questions[index];
  return <div className="content interview-page"><section className="page-heading"><div className="eyebrow">AI INTERVIEW STUDIO</div><h1>Mock interview</h1><p>One question at a time, with feedback based on your actual answer.</p></section><section className="interview-progress"><span>Question {index + 1} of {questions.length}</span><div className="progress-bar"><i style={{ width: `${(index / questions.length) * 100}%` }} /></div></section><section className="interview-room"><div className="panel question-panel"><span className="question-type">{question.type}</span><h2>{question.question}</h2><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer here..." /><div className="interview-actions"><button className="secondary-light" type="button" onClick={startVoice} disabled={listening}><Mic size={16} /> {listening ? 'Listening...' : 'Voice optional'}</button><button className="text-btn" type="button" onClick={() => { setAnswer(''); setIndex(Math.min(index + 1, questions.length)); }}><SkipForward size={15} /> Skip</button><button className="primary" type="button" onClick={submit} disabled={loading}>{loading ? 'Evaluating...' : 'Submit answer'} <ArrowRight size={16} /></button></div>{error && <p className="form-error">{error}</p>}</div><aside className="panel interview-side"><div className="eyebrow">SESSION</div><h2>{setup.role || dashboard.target_role}</h2><p>{setup.type} · {setup.difficulty} · {setup.duration}</p><div className="session-note">Your answer is evaluated for relevance, structure, communication, evidence, and problem solving.</div></aside></section></div>;
}

function Setup({ setup, update, start, loading, error }) { return <div className="content interview-page"><section className="page-heading"><div className="eyebrow">AI INTERVIEW STUDIO</div><h1>Practice with purpose</h1><p>Build confidence with a personalized interview session.</p></section><section className="panel interview-setup"><form className="interview-form" onSubmit={start}><label>Target role<input value={setup.role} onChange={update('role')} placeholder="Python Developer" required /></label><label>Interview type<select value={setup.type} onChange={update('type')}><option>Mixed</option><option>Technical</option><option>HR</option><option>Behavioral</option></select></label><label>Difficulty<select value={setup.difficulty} onChange={update('difficulty')}><option>Easy</option><option>Medium</option><option>Hard</option></select></label><label>Duration<select value={setup.duration} onChange={update('duration')}><option>10 minutes</option><option>20 minutes</option><option>30 minutes</option></select></label><label>Company optional<input value={setup.company} onChange={update('company')} placeholder="Company name" /></label><label className="wide-field">Job description optional<textarea value={setup.jobDescription} onChange={update('jobDescription')} placeholder="Paste the job description for a more targeted session..." /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Preparing interview...' : 'Start mock interview'} <ArrowRight size={16} /></button></form></section></div>; }

function Report({ reviews, history, onRestart }) { const overall = Math.round(reviews.reduce((sum, item) => sum + item.review.score, 0) / reviews.length); return <div className="content interview-page"><section className="page-heading"><div className="eyebrow">SESSION COMPLETE</div><h1>Interview report</h1><p>Use this feedback to improve your next attempt, not to memorize a script.</p></section><section className="interview-report"><div className="report-score"><span>OVERALL SCORE</span><strong>{overall}<small>/100</small></strong><p>{overall >= 70 ? 'Solid foundation. Keep sharpening your evidence.' : 'Focus on structure and specific examples next.'}</p></div><div className="review-list">{reviews.map((item, reviewIndex) => <article className="review-card" key={`${item.question}-${reviewIndex}`}><b>Question {reviewIndex + 1}</b><h3>{item.question}</h3><p className="answer-copy">{item.answer}</p><strong>{item.review.score}/100</strong><p>{item.review.feedback}</p><small>Suggested structure: {item.review.suggested_structure}</small></article>)}</div></section><button className="primary" onClick={onRestart}>Start another interview <ArrowRight size={16} /></button>{history.length > 0 && <section className="panel history-panel"><div className="eyebrow">PAST ANSWERS</div><h2>Interview history</h2>{history.slice(0, 8).map((item) => <div className="history-row" key={item.id}><span>{item.role}</span><b>{item.score}/100</b></div>)}</section>}</div>; }
