CREATE DATABASE IF NOT EXISTS career_copilot CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE career_copilot;

CREATE TABLE IF NOT EXISTS user (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS resume (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, filename VARCHAR(255) NOT NULL, extracted_text LONGTEXT NOT NULL, analysis JSON NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES user(id));
CREATE TABLE IF NOT EXISTS job_analysis (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, resume_id INT, role VARCHAR(160) NOT NULL, description LONGTEXT NOT NULL, result JSON NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES user(id), FOREIGN KEY (resume_id) REFERENCES resume(id));
CREATE TABLE IF NOT EXISTS interview_result (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, role VARCHAR(160) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, score INT NOT NULL, feedback TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES user(id));
