import React, { useEffect, useState } from 'react';
import { ArrowUpRight, BriefcaseBusiness, FileText, FileSearch, Gauge, LayoutDashboard, LogOut, Menu, MessageSquare, Route, Search, Sparkles, Target, UsersRound, WandSparkles, X } from 'lucide-react';
import { api, auth } from './services/api';
import ATSCompatibility from './components/ATSCompatibility';
import AuthFlow from './components/AuthFlow';
import PersonalCareerRoadmap from './components/PersonalCareerRoadmap';
import SkillGapAnalyzer from './components/SkillGapAnalyzer';
import Achievements from './components/Achievements';
import MockInterview from './components/MockInterview';
import PlacementReadiness from './components/PlacementReadiness';
import JobApplications from './components/JobApplications';
import GDPractice from './components/GDPractice';
import ResumeBulletImprover from './components/ResumeBulletImprover';
import JobDescriptionAnalyzer from './components/JobDescriptionAnalyzer';
import './auth.css';
import './auth-complete.css';
import './auth-centered.css';
import './roadmap.css';
import './roadmap-overrides.css';
import './skill-gap.css';
import './achievements.css';
import './interview.css';
import './career-tools.css';

const emptyDashboard = { user: { name: 'there' }, resume: null, resume_id: null, ats: null, roles: [], roadmap: [], interview_progress: 0, target_role: '' };
const initials = (name = '') => name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'CC';

export default function App() {
  const [token, setToken] = useState(() => localStorage.getItem('career_token'));
  const [active, setActive] = useState('Overview');
  const [mobile, setMobile] = useState(false);
  const [dashboard, setDashboard] = useState(emptyDashboard);
  const [loading, setLoading] = useState(Boolean(token));
  const [error, setError] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  useEffect(() => { if (!token) return; setLoading(true); auth.dashboard().then(setDashboard).catch((err) => { localStorage.removeItem('career_token'); setToken(null); setError(err.message); }).finally(() => setLoading(false)); }, [token]);
  useEffect(() => { if (!token || active !== 'Overview' || loading) return undefined; const button = [...document.querySelectorAll('button')].find((item) => item.textContent.includes('Run a new analysis')); if (!button) return undefined; const openResumeLab = () => setActive('Resume lab'); button.addEventListener('click', openResumeLab); return () => button.removeEventListener('click', openResumeLab); }, [token, active, loading]);
  const logout = () => { localStorage.removeItem('career_token'); setToken(null); setDashboard(emptyDashboard); };
  const [onboarding, setOnboarding] = useState(false);
  if (!token) return <AuthFlow onAuthenticated={(newToken, needsOnboarding) => { localStorage.setItem('career_token', newToken); setToken(newToken); setOnboarding(needsOnboarding); }} initialError={error} />;
  if (onboarding) return <AuthFlow onboarding token={token} onComplete={() => { setOnboarding(false); setActive('Overview'); setMobile(false); setLoading(true); auth.dashboard().then(setDashboard).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }} />;
  const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Placement Readiness', icon: Gauge }, { label: 'My Applications', icon: BriefcaseBusiness }, { label: 'Resume lab', icon: FileText }, { label: 'Resume Bullet Improver', icon: WandSparkles }, { label: 'Job Description Analyzer', icon: FileSearch }, { label: 'ATS compatibility', icon: Target }, { label: 'Job match', icon: Target }, { label: 'Interview prep', icon: MessageSquare }, { label: 'GD Practice', icon: UsersRound }, { label: 'Learning path', icon: Route }, { label: 'Personal Career Roadmap', icon: Route }, { label: 'Skill Gap Analyzer', icon: Target }, { label: 'Achievements', icon: Sparkles }];
  const searchResults = nav.filter(({ label }) => label.toLowerCase().includes(searchQuery.toLowerCase().trim()));
  const goToSearchResult = (label) => { setActive(label); setSearchQuery(''); setSearchOpen(false); };
  return <div className="app-shell"><aside className={mobile ? 'sidebar open' : 'sidebar'}><Brand /><div className="workspace-label">WORKSPACE</div><nav>{nav.map(({ label, icon: Icon }) => <button className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => { setActive(label); setMobile(false); }} key={label}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="upgrade"><Sparkles size={16} /><strong>Unlock your edge</strong><p>Get deeper insights with Copilot Pro.</p></div><button className="nav-item" onClick={logout}><LogOut size={18} />Sign out</button><div className="profile"><div className="avatar">{initials(dashboard.user.name)}</div><div><b>{dashboard.user.name}</b><small>{dashboard.user.email}</small></div><span className="online-dot" /></div></div></aside><main className="main"><header><button className="icon-btn menu" onClick={() => setMobile(!mobile)}>{mobile ? <X size={20} /> : <Menu size={20} />}</button><div className="crumb"><span>Workspace</span><b>/</b><strong>{active}</strong></div><div className="header-actions"><div className={searchOpen ? 'search-wrap open' : 'search-wrap'}><button className="icon-btn" onClick={() => setSearchOpen(!searchOpen)} aria-label="Search workspace"><Search size={18} /></button>{searchOpen && <div className="search-panel"><input autoFocus value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') setSearchOpen(false); if (event.key === 'Enter' && searchResults[0]) goToSearchResult(searchResults[0].label); }} placeholder="Search workspace..." aria-label="Search workspace" />{searchQuery && <div className="search-results">{searchResults.length ? searchResults.map(({ label }) => <button key={label} onClick={() => goToSearchResult(label)}>{label}</button>) : <span>No matching workspace</span>}</div>}</div>}</div><div className="avatar small">{initials(dashboard.user.name)}</div></div></header>{loading ? <div className="state"><div className="spinner" />Loading your career signal...</div> : <Feature active={active} dashboard={dashboard} onRefresh={() => auth.dashboard().then(setDashboard)} onNavigate={setActive} />}</main></div>;
}
function Brand() { return <div className="brand"><span className="brand-mark"><Sparkles size={17} /></span> career<span>copilot</span></div>; }
function Auth({ onAuthenticated, initialError }) { const [register, setRegister] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(initialError || ''); const [loading, setLoading] = useState(false); const update = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const result = register ? await auth.register(form) : await auth.login({ email: form.email, password: form.password }); onAuthenticated(result.token); } catch (err) { setError(err.message); } finally { setLoading(false); } }; return <div className="auth-page"><div className="auth-art"><Brand /><div className="art-copy"><div className="eyebrow"><span /> CAREER INTELLIGENCE, REIMAGINED</div><h1>Your next move,<br /><em>made clearer.</em></h1><p>Turn your potential into a plan with an AI career partner that knows where you want to go.</p></div><div className="art-foot">Trusted by ambitious students and early-career builders <span>✦</span></div></div><div className="auth-form"><div className="auth-inner"><div className="mobile-brand"><Brand /></div><div className="form-heading"><h2>{register ? 'Create your account' : 'Welcome back'}</h2><p>{register ? 'Start building your career advantage.' : 'Pick up where your career story left off.'}</p></div><form onSubmit={submit}>{register && <label>Full name<input value={form.name} onChange={update('name')} placeholder="Alex Morgan" required /></label>}<label>Email address<input value={form.email} onChange={update('email')} type="email" placeholder="you@example.com" required /></label><label>Password<input value={form.password} onChange={update('password')} type="password" placeholder="At least 8 characters" minLength="8" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={loading}>{loading ? 'Connecting...' : register ? 'Create account' : 'Sign in'} <ArrowUpRight size={16} /></button></form><p className="switch">{register ? 'Already have an account?' : "Don't have an account?"} <button onClick={() => { setRegister(!register); setError(''); }}>{register ? 'Sign in' : 'Create one'}</button></p></div></div></div>; }
function Feature({ active, dashboard, onRefresh, onNavigate }) { if (active === 'Resume lab') return <ResumeLab dashboard={dashboard} onRefresh={onRefresh} />; if (active === 'Placement Readiness') return <PlacementReadiness dashboard={dashboard} onNavigate={onNavigate} />; if (active === 'My Applications') return <JobApplications />; if (active === 'Resume Bullet Improver') return <ResumeBulletImprover />; if (active === 'Job Description Analyzer') return <JobDescriptionAnalyzer />; if (active === 'GD Practice') return <GDPractice />; if (active === 'ATS compatibility') return <ATSCompatibility />; if (active === 'Job match') return <JobMatch dashboard={dashboard} />; if (active === 'Interview prep') return <MockInterview dashboard={dashboard} />; if (active === 'Learning path') return <Roadmap dashboard={dashboard} />; if (active === 'Personal Career Roadmap') return <PersonalCareerRoadmap dashboard={dashboard} />; if (active === 'Skill Gap Analyzer') return <SkillGapAnalyzer />; if (active === 'Achievements') return <Achievements dashboard={dashboard} />; return <Overview dashboard={dashboard} onNavigate={onNavigate} />; }
function Overview({ dashboard }) { const resumeScore = dashboard.resume?.score || 0; const atsScore = dashboard.ats?.score || 0; return <div className="content"><section className="welcome"><div><div className="eyebrow"><span /> YOUR CAREER SIGNAL</div><h1>Good morning, {dashboard.user.name?.split(' ')[0] || 'there'}<span>.</span></h1><p>Here is your career signal for today. Small moves compound.</p></div><button className="primary">Run a new analysis <ArrowUpRight size={16} /></button></section><section className="signal-grid"><Metric label="Resume score" value={resumeScore} suffix="/100" color="coral" /><Metric label="ATS compatibility" value={atsScore} suffix="%" color="blue" /><Metric label="Top role match" value={dashboard.roles[0]?.match || 0} suffix="%" color="green" /><Metric label="Interview prep" value={dashboard.interview_progress} suffix="%" color="gold" /></section><div className="dashboard-grid"><Panel title="Resume health" eyebrow="YOUR SIGNAL"><div className="score-row"><div className="score-ring" style={{ background: `radial-gradient(closest-side,#fff 77%,transparent 78% 100%),conic-gradient(var(--coral) ${resumeScore}%,#f4e5df 0)` }}><strong>{resumeScore}</strong><span>/ 100</span></div><div><h3>{resumeScore ? 'Strong foundation' : 'Upload your resume'}</h3><p>{resumeScore ? 'Your resume has been analyzed. Open Resume lab for targeted improvements.' : 'Upload a PDF to unlock resume, ATS, and role insights.'}</p></div></div></Panel><Panel title="Best-fit roles" eyebrow="OPPORTUNITY RADAR">{dashboard.roles.length ? dashboard.roles.map((item) => <div className="role-row" key={item.role}><div className="role-name"><b>{item.role}</b><small>{item.reason || `${item.matched_skills?.length || 0} skills matched`}</small></div><div className="match"><strong>{item.match}%</strong><span>match</span></div></div>) : <Empty text="Analyze a resume to discover your best-fit roles." />}</Panel><Panel title="Learning path" eyebrow="YOUR MOMENTUM"><RoadmapItems items={dashboard.roadmap} /></Panel><Panel title="Career snapshot" eyebrow="COPILOT SUGGESTION"><p className="panel-copy">{dashboard.ats ? `${dashboard.ats.missing_keywords.length} skills are missing from your latest target role.` : 'Run an ATS analysis to find the skills that will move your application forward.'}</p></Panel></div></div>; }
function Panel({ title, eyebrow, children }) { return <section className="panel"><div className="panel-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div></div>{children}</section>; }
function Metric({ label, value, suffix, color }) { return <div className={'metric ' + color}><div className="metric-top"><span className="metric-icon"><Sparkles size={15} /></span></div><small>{label}</small><div className="metric-value">{value}<sup>{suffix}</sup></div><div className="metric-progress"><i style={{ width: `${value}%` }} /></div></div>; }
function Empty({ text }) { return <p className="empty">{text}</p>; }
function ErrorMessage({ error }) { return error && <p className="form-error">{error}</p>; }
function ResumeLab({ dashboard, onRefresh }) { const [file, setFile] = useState(null); const [result, setResult] = useState(dashboard.resume); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const analyze = async (event) => { event.preventDefault(); if (!file) return setError('Choose a PDF resume first.'); if (file.type !== 'application/pdf' || file.size > 5 * 1024 * 1024) return setError('Resume must be a PDF smaller than 5 MB.'); setLoading(true); setError(''); try { const data = await api.resume(file); setResult(data.analysis); await onRefresh(); } catch (err) { setError(err.message); } finally { setLoading(false); } }; return <div className="content"><section className="page-heading"><div className="eyebrow">RESUME INTELLIGENCE</div><h1>Resume lab</h1><p>Turn your resume into a sharper signal for the roles you want.</p></section><section className="tool-grid"><Panel title="Analyze a resume" eyebrow="PDF UPLOAD"><form onSubmit={analyze}><label className="upload-box"><input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files[0])} /><UploadLabel file={file} /></label><ErrorMessage error={error} /><button className="primary" disabled={loading}>{loading ? 'Analyzing...' : 'Analyze resume'} <ArrowUpRight size={16} /></button></form></Panel>{result ? <AnalysisCard result={result} /> : <Panel title="Your report will appear here" eyebrow="INSIGHT REPORT"><Empty text="Upload a readable PDF to see skills, strengths, gaps, and recommendations." /></Panel>}</section></div>; }
function UploadLabel({ file }) { return <span className="upload-label"><FileText size={22} /><b>{file ? file.name : 'Drop your PDF here'}</b><small>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : 'PDF only, up to 5 MB'}</small></span>; }
function AnalysisCard({ result }) { return <Panel title={`Score: ${result.score}/100`} eyebrow="INSIGHT REPORT"><div className="tag-list">{result.sections.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><h3>Strengths</h3><ul>{result.strengths.map((item) => <li key={item}>{item}</li>)}</ul><h3>Gaps to close</h3><ul>{result.weaknesses.map((item) => <li key={item}>{item}</li>)}</ul><h3>Recommendations</h3><ul>{result.suggestions.map((item) => <li key={item}>{item}</li>)}</ul></Panel>; }
function JobMatch({ dashboard }) { const [role, setRole] = useState(''); const [skills, setSkills] = useState(dashboard.resume?.sections?.skills?.join(', ') || ''); const [description, setDescription] = useState(''); const [roles, setRoles] = useState(dashboard.roles); const [ats, setAts] = useState(dashboard.ats); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const data = await api.jobs(skills.split(',').map((item) => item.trim()).filter(Boolean), role); setRoles(data.roles); if (description && dashboard.resume_id) setAts(await api.ats(dashboard.resume_id, role, description)); } catch (err) { setError(err.message); } finally { setLoading(false); } }; return <div className="content"><section className="page-heading"><div className="eyebrow">OPPORTUNITY RADAR</div><h1>Find your fit</h1><p>Compare your current skills with the roles that need them.</p></section><div className="tool-grid"><Panel title="Your target" eyebrow="ROLE MATCH"><form onSubmit={submit}><label>Target role<input value={role} onChange={(event) => setRole(event.target.value)} placeholder="Frontend Developer" /></label><label>Skills, comma separated<input value={skills} onChange={(event) => setSkills(event.target.value)} placeholder="React, JavaScript, Git" /></label><label>Job description <span className="optional">optional, enables ATS score</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Paste the job description..." /></label><ErrorMessage error={error} /><button className="primary" disabled={loading}>{loading ? 'Analyzing...' : 'Analyze fit'} <ArrowUpRight size={16} /></button></form></Panel><Panel title="Recommended roles" eyebrow="MATCH RESULTS">{roles.length ? roles.map((item) => <div className="role-row" key={item.role}><div className="role-name"><b>{item.role}</b><small>{item.reason || `${item.matched_skills?.length || 0} skills matched`}</small></div><div className="match"><strong>{item.match}%</strong><span>match</span></div></div>) : <Empty text="Enter your skills to find role recommendations." />}{ats && <div className="ats-result"><b>ATS compatibility: {ats.score}%</b><small>Missing: {ats.missing_keywords.join(', ') || 'None'}</small></div>}</Panel></div></div>; }
function Interview({ dashboard }) { const [role, setRole] = useState('Frontend Developer'); const [questions, setQuestions] = useState([]); const [answer, setAnswer] = useState(''); const [feedback, setFeedback] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const generate = async () => { setLoading(true); setError(''); try { const data = await api.questions(role, dashboard.resume?.sections?.skills || [], ''); setQuestions(data.questions); setFeedback(null); setAnswer(''); } catch (err) { setError(err.message); } finally { setLoading(false); } }; const evaluate = async () => { setLoading(true); setError(''); try { setFeedback(await api.evaluate(role, questions[0].question, answer)); } catch (err) { setError(err.message); } finally { setLoading(false); } }; return <div className="content"><section className="page-heading"><div className="eyebrow">AI INTERVIEW STUDIO</div><h1>Practice with purpose</h1><p>Generate focused questions and get structured feedback on your answer.</p></section><div className="tool-grid"><Panel title="Interview setup" eyebrow="START SESSION"><label>Target role<input value={role} onChange={(event) => setRole(event.target.value)} /></label><ErrorMessage error={error} /><button className="primary" onClick={generate} disabled={loading}>{loading ? 'Generating...' : 'Generate questions'} <ArrowUpRight size={16} /></button></Panel><Panel title="Practice room" eyebrow="YOUR QUESTIONS">{questions.length ? <div><span className="question-type">{questions[0].type}</span><h3>{questions[0].question}</h3><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Write your answer here..." /><button className="primary" onClick={evaluate} disabled={loading || !answer.trim()}>{loading ? 'Evaluating...' : 'Evaluate answer'} <ArrowUpRight size={16} /></button>{feedback && <div className="feedback"><b>{feedback.score}/100</b><p>{feedback.feedback}</p></div>}</div> : <Empty text="Generate questions to begin your practice session." />}</Panel></div></div>; }
function Roadmap({ dashboard }) { return <div className="content"><section className="page-heading"><div className="eyebrow">YOUR MOMENTUM</div><h1>Learning path</h1><p>A practical next step for each skill gap in your target direction.</p></section><section className="panel roadmap-panel"><RoadmapItems items={dashboard.roadmap} detailed />{!dashboard.roadmap.length && <Empty text="Analyze a resume and target role to generate your roadmap." />}</section></div>; }
function RoadmapItems({ items, detailed }) { return items.map((item, index) => <div className="road-item" key={item.title}><div className={index === 0 ? 'node current' : 'node'}>{index + 1}</div><div><small>{item.status}</small><b>{item.title}</b><span>{item.category}{detailed && item.resource ? `: ${item.resource}` : ''}</span></div></div>); }